#!/bin/bash
mkdir -p dist
cp dice.py dist
cp README.md dist
cp node_modules/pyodide/console-v2.html dist/index.html
cp node_modules/pyodide/pyodide.mjs dist
cp node_modules/pyodide/pyodide.mjs.map dist
cp node_modules/pyodide/pyodide-lock.json dist
cp node_modules/pyodide/pyodide.asm.wasm dist
cp node_modules/pyodide/pyodide.asm.js dist
cp node_modules/pyodide/python_stdlib.zip dist
